#+TITLE: Philip Ye
#+LANGUAGE: en
#+OPTIONS: toc:nil H:10 tex:t
#+STARTUP: odd hidestars indent showall
#+INCLUDE: personal_info.org
#+LaTeX_CLASS: article
#+LaTeX_HEADER: \usepackage{mycv}
#+LaTeX_HEADER: \hypersetup{hidelinks}
#+LaTeX_HEADER: \usepackage{enumitem}
#+LaTeX_HEADER: \setlist{nolistsep}
#+LaTeX_HEADER: \pagenumbering{gobble}
#+LaTeX_CLASS_OPTIONS: [letterpaper]

{{{SUBTITLEROWS}}}
{{{HEADER}}}
* Summary

Server side engineer focused on Cloud Management and CDN 

* Skills

- *Languages*: /Experienced in/ Node.js, Go, Python, C; /Familar with/ C++
- *Platforms*: /Experienced/ Linux developer, /Experienced in/ POSIX, REST, HTTP
- *Tools*: /Expert in/ vim, /Familiar with/ git, tmux, emacs
- *Open Source Projects*: /Experienced in/ Consul, /Familiar with/ Redis, RabbitMQ, Mongo

* Experience

*** Senior Software Engineer at Cisco
***** Oct 2015 - Now
V2PC(Virtual Video Platform - Controller), a video cloud platform for
controlling cloud based dataplane services (including but not limited
to video Recorders/Codecs/JITP Packagers .etc) owned by Cisco 
\vspace{0.1in}

- *Baremetal Support in V2PC*: Design and impelement the whole feature to manage
  baremetal devices via PXE and Cobbler, including but not limited to lifecycle,
  provision and monitoring .etc
- *Automation Framework* Rework: Design and reimplement an Object Oriented 
  automation framework for V2PC which is cross-platform, flexible, extensible,
  and reliable.
- *Package Management*: Design the package layout for applications running on
  V2PC which bundles NPM and RPMs into a /package/. Design and implement
  PackageManager which supports package CRUD via REST APIs
- *API Driven Platform Upgrade*: Design and implement UpgradeMgr which provides
  REST API in the frontend and handles all the platform upgrade logic in the
  backend 
- *Customer Case Resolve*: Resolve customer issues in production
  environment. Experienced in live debug and issue tracking. 
- *Performance Enhancement*: At the core of V2PC stands DocServer which supports
  PUBSUB for document store and notification. By investigating into performance
  bottlenecks and resolving them, the number of notification clients of
  DocServer successfully is scaled up 5x


*** Software Engineer at Cisco
***** Mar 2013 - Sep 2015
VDS-IS (Video Distribution System - Internet Streamer), cisco's video
centric CDN solution for Service Providers which supports RTSP,
ABR(HLS, HSS, DASH)

\vspace{0.1in}
- *Support Engineer*: Serves as last defender of customer cases,
  analyzing coredumps in production environment, resolving customer
  issues during major events like Melbourne Cup 
- *Keep Alive Enhance*: Re-Implemented the perl based Keep Alive system in the
  whole VDS-IS solution to eliminate flapping issues in customer's production
  environment 
- Internal Hackthon: Second Prize Winer for a ELK based prototype to
  detect failure node in CDN

* Education

*** Master in Shanghai Jiao Tong University
***** Sep 2010 - Apr 2013
/Master of Electronic Engineering/, major in Video Processing
*** Bachelor in Shanghai Jiao Tong University
***** Sep 2006 - Jun 2010
/Bachelor of Electronic Engineering/, GPA 83/100